# Generated by Django 4.2.2 on 2023-07-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('vision', models.CharField(choices=[('ANEMO', 'Anemo'), ('GEO', 'Geo'), ('ELECTRO', 'Electro'), ('DENDRO', 'Dendro'), ('HYDRO', 'Hydro'), ('PYRO', 'Pyro'), ('CRYO', 'Cryo'), ('FUTURE1', 'Future Element')], max_length=64)),
                ('weapon', models.CharField(choices=[('SWORD', 'Sword'), ('POLEARM', 'Polearm'), ('CATALYST', 'Catalyst'), ('BOW', 'Bow'), ('FUTURE1', 'Future Weapon 1'), ('FUTURE2', 'Future Weapon 2')], max_length=64)),
                ('nation', models.CharField(choices=[('MONDSTADT', 'Mondstadt'), ('LIYUE', 'Liyue'), ('INAZUMA', 'Inazuma'), ('SUMERU', 'Sumeru'), ('FONTAINE', 'Fontaine'), ('NATLAN', 'Natlan'), ('SNEZHNAYA', 'Snezhnaya'), ('KHAENRIAH', "Khaenri'ah")], max_length=64)),
                ('rarity', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
                ('release', models.DateField()),
                ('title', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=64)),
                ('constellation_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': (['name'],),
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('talent_type', models.CharField(max_length=64)),
                ('talent_name', models.CharField(max_length=64)),
                ('talent_desc', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='rest_api.character')),
            ],
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_number', models.PositiveSmallIntegerField()),
                ('con_name', models.CharField(max_length=64)),
                ('con_desc', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constellations', to='rest_api.character')),
            ],
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('character_id', 'name'), name='unique_character'),
        ),
        migrations.AddConstraint(
            model_name='talent',
            constraint=models.UniqueConstraint(fields=('order', 'talent_type', 'talent_name', 'talent_desc'), name='unique_talent'),
        ),
        migrations.AddConstraint(
            model_name='constellation',
            constraint=models.UniqueConstraint(fields=('con_number', 'con_name', 'con_desc'), name='unique_constellation'),
        ),
    ]
