# Generated by Django 4.2.2 on 2023-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_release_character_release_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='vision',
            field=models.CharField(choices=[('ANEMO', 'Anemo'), ('GEO', 'Geo'), ('ELECTRO', 'Electro'), ('DENDRO', 'Dendro'), ('HYDRO', 'Hydro'), ('PYRO', 'Pyro'), ('CRYO', 'Cryo'), ('MULTI', 'Multi'), ('FUTURE1', 'Future Element')], max_length=64),
        ),
    ]
