# Generated by Django 4.2.2 on 2023-09-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_character_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.CharField(choices=[('SWORD', 'Sword'), ('POLEARM', 'Polearm'), ('CLAYMORE', 'Claymore'), ('CATALYST', 'Catalyst'), ('BOW', 'Bow'), ('FUTURE1', 'Future Weapon 1'), ('FUTURE2', 'Future Weapon 2')], max_length=64),
        ),
    ]
