# Generated by Django 4.2.2 on 2023-07-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='release',
            field=models.CharField(max_length=5),
        ),
    ]
