# Generated by Django 4.2.2 on 2023-07-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_character_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='release',
            new_name='release_version',
        ),
    ]
