# Generated by Django 4.2.2 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_character_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthday',
            field=models.CharField(max_length=10),
        ),
    ]
