# Generated by Django 4.2.2 on 2023-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_character_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='nation',
            field=models.CharField(choices=[('MONDSTADT', 'Mondstadt'), ('LIYUE', 'Liyue'), ('INAZUMA', 'Inazuma'), ('SUMERU', 'Sumeru'), ('FONTAINE', 'Fontaine'), ('NATLAN', 'Natlan'), ('SNEZHNAYA', 'Snezhnaya'), ('KHAENRIAH', "Khaenri'ah"), ('UNKNOWN', 'Unknown')], max_length=64),
        ),
    ]
